# Generated by Django 5.2.1 on 2025-05-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
